name: Build & Tests

on:
  push:
    branches:
      - main
      - develop
    pull_request:
      branches:
        - develop

jobs:
  main:
    runs-on: ubuntu-latest
    name: Build Docker image, download data, run scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Data
        uses: ./ # using private root action
        with:
          script: 'download_data.R'
      
      - name: Create Monthly Expense plot
        uses: ./  # using private root action
        with:
          script: 'plot/R/monthly_expense.R'
