name: Build & Tests

on:
  push:
    branches:
      - main
      - develop
    pull_request:
      branches:
        - develop

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/personal-finance-analytics@v1
        with:
          script: 'plot/R/monthly_expense.R'

