name: Build & Tests

on:
  push:
    branches:
      - main
      - develop
    pull_request:
      branches:
        - develop

jobs:
  main:
    runs-on: ubuntu-latest
    name: Build Docker image, download data, run scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create ./data directory
        run: |
          mkdir -p data
      
      - name: Download Data
        env:
            NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
        uses: ./ # using private root action
        with:
          script: 'download_data.R'
      
      - name: Create Monthly Expense plot
        uses: ./  # using private root action
        with:
          script: 'plot/R/monthly_expense.R'

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Send mail
        env:
          MAILJET_USER: ${{ secrets.MAILJET_USER }}
          MAILJET_CREDENTIAL: ${{ secrets.MAILJET_CREDENTIAL }}
        run: |
          pip install mailjet_rest
          python email/send.py